#!/bin/bash

#  ----------------
# | BASH - Aliases |
#  ----------------

# Program startup options
alias cmatrix='cmatrix -u 5 -C green'                           # Start with a speed of '5' and set the color
alias cp='cp -i' 					        # Confirm before overwriting something
alias exa='exa -G --color=always --group-directories-first'     # '-G' means 'grid mode'

# Drop-in program replacements
alias ls='exa'                                                  # Replace ls with 'exa': 
#                                                               # faster, written in Rust
alias vi='vim'
alias visudo='sudo vim'
alias find='fd'                                                 # Again... faster, written in Rust
alias lolcat='dotacat'                                          # See above

# Navigation
alias lt='exa -TL 2'
alias lsa='exa -alu --git --time-style long-iso'                # More info about hidden files (and git status)
alias lsd='exa -D'                                              # List only directories

# Terminal clearing and teleportation
alias cl='clear; sleep 0.01; ls'                                # Clear the terminal and list directories above prompt
alias cdd='cd; clear; sleep 0.01; exa -xDG'                     # Teleport to $HOME
alias cdc='cd ~/.config; clear; sleep 0.01; git status'         # Teleport to ~/.config
alias cddots='cd ~/.dotfiles; clear; sleep 0.01; git status'    # Copy of ~/.config I'm working with as an experiment
alias :q='cd ..'                                                # Helpful for post-vim-session navigation

# Quick simple actions
alias rebash='cdd; sleep 0.01; exec bash;'                      # Reload bash, for example when testing configurations
alias wiki='vi wiki/index.wiki'

# Since I'll never remember how to do this again:
alias ssh-agent-cyg='eval `ssh-agent -s`'                       # HINT: It's the tilde quotes for fuck's sake

# Correcting improperly assigned configuration paths
alias nvidia-settings="nvidia-settings --config=~/.config/nvidia-settings.rc"
